---
- name: Authorize the necessary ports permanently
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
    immediate: yes
  with_items:
  - 6443/tcp
  - 2379-2380/tcp
  - 10250/tcp
  - 10257/tcp
  - 10259/tcp

- import_tasks: init-control-plane-setup.yml
  when: kubernetes_role == 'primary_control_plane'

- import_tasks: join-control-plane-setup.yml
  when: kubernetes_role == 'secondary_control_plane'