apiVersion: v1
kind: ConfigMap
metadata:
  name: loki
  namespace: loki
  labels:
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "3.3.2"
data:
  config.yaml: |
    auth_enabled: true
    chunk_store_config:
      chunk_cache_config:
        background:
          writeback_buffer: 500000
          writeback_goroutines: 1
          writeback_size_limit: 500MB
        default_validity: 0s
        memcached:
          batch_size: 4
          parallelism: 5
        memcached_client:
          addresses: loki-results-cache.loki.svc.cluster.local:11211
          consistent_hash: true
          max_idle_conns: 72
          timeout: 2000ms
    common:
      compactor_address: 'http://loki-compactor:3100'
      path_prefix: /var/loki
      replication_factor: 3
      storage:
        type: s3 
        s3:
          bucketnames: loki-chunks
          endpoint: minio-storage.minio.svc.cluster.local:9000
          access_key_id: $MINIO_ACCESS_KEY
          secret_access_key: $MINIO_SECRET_KEY
          s3forcepathstyle: false
          insecure: true
    compactor:
      delete_request_store: s3
      retention_enabled: true
    frontend:
      scheduler_address: loki-query-scheduler.loki.svc.cluster.local:9095
      tail_proxy_url: http://loki-querier.loki.svc.cluster.local:3100
    frontend_worker:
      scheduler_address: loki-query-scheduler.loki.svc.cluster.local:9095
    index_gateway:
      mode: simple
    ingester:
      chunk_encoding: snappy
    limits_config:
      allow_structured_metadata: true
      max_cache_freshness_per_query: 10m
      query_timeout: 300s
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      retention_period: 672h
      split_queries_by_interval: 15m
      volume_enabled: true
    memberlist:
      join_members:
      - loki-memberlist
    pattern_ingester:
      enabled: true
    querier:
      max_concurrent: 4
      query_ingesters_within: 1h
    query_scheduler:
      max_outstanding_requests_per_tenant: 32000
      use_scheduler_ring: true
    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          background:
            writeback_buffer: 500000
            writeback_goroutines: 1
            writeback_size_limit: 500MB
          default_validity: 12h
          memcached_client:
            addresses: loki-results-cache.loki.svc.cluster.local:11211
            consistent_hash: true
            timeout: 500ms
            update_interval: 1m
    ruler:
      enable_api: true
      enable_sharding: true
      storage:
        type: s3
        s3:
          bucketnames: loki-ruler
          endpoint: minio-storage.minio.svc.cluster.local:9000
          access_key_id: $MINIO_ACCESS_KEY
          secret_access_key: $MINIO_SECRET_KEY
          s3forcepathstyle: false
          insecure: true
      wal:
        dir: /var/loki/ruler-wal
      remote_write
        enabled: true
        clients: 
          prometheus:
            url: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
    runtime_config:
      file: /etc/loki/runtime-config/runtime-config.yaml
    schema_config:
      configs:
      - from: "2024-04-01"
        index:
          period: 24h
          prefix: loki_index_
        object_store: s3
        schema: v13
        store: tsdb
    server:
      grpc_listen_port: 9095
      http_listen_port: 3100
      http_server_read_timeout: 600s
      http_server_write_timeout: 600s
    storage_config:
      aws:
        bucketnames: loki-chunks
        endpoint: minio-storage.minio.svc.cluster.local:9000
        access_key_id: $MINIO_ACCESS_KEY
        secret_access_key: $MINIO_SECRET_KEY
        s3forcepathstyle: false
        insecure: true
      boltdb_shipper:
        index_gateway_client:
          server_address: dns+loki-index-gateway-headless.loki.svc.cluster.local:9095
      hedging:
        at: 250ms
        max_per_second: 20
        up_to: 3
      tsdb_shipper:
        index_gateway_client:
          server_address: dns+loki-index-gateway-headless.loki.svc.cluster.local:9095
    tracing:
      enabled: false