replicaCount: 3

image:
  repository: otel/opentelemetry-collector-contrib
  pullPolicy: IfNotPresent
  tag: "0.106.1"

imagePullSecrets: []
nameOverride: "otelcollector"
fullnameOverride: "otelcollector"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8889
  health:
    name: health-http
    port: 13133
    path: /
    protocol: TCP
  otlpGRPC:
    name: otlp-grpc
    port: 4317
    protocol: TCP
  otlpHTTP:
    name: otlp-http 
    port: 4318
    protocol: TCP
  metricHTTP:
    name: metric-http
    port: 8889
    protocol: TCP
  promHTTP:
    name: prom-http
    port: 8888
    protocol: TCP

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: otelcol.willbrid.com
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: willbridcom
    hosts:
    - otelcol.willbrid.com

configmap:
  mountPath: /etc/otelcol-contrib/config.yaml
  subPath: config.yaml
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
    processors:
      batch:
      memory_limiter:  
        limit_mib: 1500  
        spike_limit_mib: 512
        check_interval: 5s
    extensions:
      health_check: {}
    exporters:
      prometheus:
        endpoint: "0.0.0.0:8889"
      prometheusremotewrite:
        endpoint: "http://@promIP:9090/api/v1/write"
        tls:
          insecure: true
    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [prometheus,prometheusremotewrite]

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
