kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-storage
  namespace: minio
  labels:
    app: minio-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client
  volumeMode: Filesystem