apiVersion: v1
kind: Service
metadata:
  name: redis-store-headless
  namespace: redis
  labels:
    app: redis-store
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    name: redis-store
    protocol: TCP
  selector:
    app: redis-store