apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-file-server
  labels:
    app: static-file-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: custom-storage-class # Il faudrait remplacer cette valeur par celle de votre classe de stockage