apiVersion: v1
kind: Service
metadata:
  name: static-file-server
  labels:
    app: static-file-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: static-file-server