apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: mongo:7.0.6
        args: ["--auth"]
        ports:
        - name: tcp-port
          containerPort: 27017
          protocol: TCP
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: password
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb
              key: database
        volumeMounts:
        - name: mongodb
          mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        storageClassName: "custom-storage-class"
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi