kind: Secret
apiVersion: v1
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
data:
  password: a2V5Y2xvYWtkYXRhYmFzZXBhc3N3b3Jk   # Keycloak mariadb database password
  username: a2V5Y2xvYWtkYXRhYmFzZXVzZXI=       # Keycloak mariadb database username
type: Opaque