kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  serviceName: 'keycloak-headless'
  replicas: 3
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
      - name: keycloak-tls-certificates
        secret:
          secretName: willbridcom
      containers:
        - name: keycloak
          image: 'quay.io/keycloak/keycloak:25.0.2'
          args:
            - '-Djgroups.dns.query=keycloak-headless.keycloak'
            - '--verbose'
            - start
          ports:
            - name: https-svc
              containerPort: 8443
              protocol: TCP
            - name: http-svc
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 9000
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1700Mi
          env:
            - name: KC_HOSTNAME
              value: 'https://auth.willbrid.com'
            - name: KC_HOSTNAME_ADMIN
              value: 'https://auth.willbrid.com'
            - name: KC_HOSTNAME_STRICT
              value: 'true'
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: 'true'
            - name: KC_HTTP_ENABLED
              value: 'true'
            - name: KC_HTTP_PORT
              value: '8080'
            - name: KC_HTTPS_PORT
              value: '8443'
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /mnt/certificates/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /mnt/certificates/tls.key
            - name: KC_DB
              value: mysql
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: password
            - name: KC_DB_URL_DATABASE
              value: keycloak              # Keycloak mariadb database name
            - name: KC_DB_URL_HOST
              value: 'mariadb.mariadb.svc' # Mariadb IP or DNS
            - name: KC_DB_URL_PORT
              value: '3306'                # Mariadb port  
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
            - name: KC_CACHE
              value: ispn
            - name: KC_CACHE_STACK
              value: kubernetes
            - name: KC_PROXY
              value: passthrough
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: username
                  optional: false
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-initial-admin
                  key: password
                  optional: false
            - name: KC_TRUSTSTORE_PATHS
              value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt,/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
              scheme: HTTPS
            timeoutSeconds: 1
            periodSeconds: 1
            successThreshold: 1
            failureThreshold: 600
          volumeMounts:
          - name: keycloak-tls-certificates
            mountPath: /mnt/certificates
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30