apiVersion: v1
kind: Secret
metadata:
  name: graylog
  namespace: graylog
  labels:
    component: graylog
type: Opaque
data:
  GRAYLOG_PASSWORD_SECRET: dGVzdEB0ZXN0dGVzdEB0ZXN0
  GRAYLOG_ROOT_PASSWORD_SHA2: MTdlNDE2YjUzZmNjMmE3Mzc5ZmYyNDlhMzQzNmY2MzRjM2NiOGM1MmUzMjBjZDY1ZmY5MWQ1ZDA3ZGIwMmRiMw==
  GRAYLOG_MONGODB_URI: bW9uZ29kYjovL2dyYXlsb2c6dGVzdDIwMjR0ZXN0QGdtb25nb2RiLTAubW9uZ29kYi1oZWFkbGVzczoyNzAxNy9ncmF5bG9nP2F1dGhTb3VyY2U9Z3JheWxvZw==
  GRAYLOG_ROOT_USERNAME: YWRtaW4=
  GRAYLOG_ELASTICSEARCH_HOSTS: aHR0cHM6Ly9hZG1pbjp0ZXN0MjAyNHRlc3RAb3BlbnNlYXJjaC5vcGVuc2VhcmNoOjkyMDA=