apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog
  namespace: graylog
  labels:
    component: graylog
spec:
  serviceName: graylog
  replicas: 3
  selector:
    matchLabels:
      component: graylog
  template:
    metadata:
      labels:
        component: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:6.0.5
        command: ["/usr/bin/tini", "--", "wait-for-it", "opensearch.opensearch:9200", "--", "/docker-entrypoint.sh"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: graylog
        - secretRef:
            name: graylog
        ports:
        - name: http-port
          containerPort: 9000
          protocol: TCP
        - name: syslog-tcp
          containerPort: 1514
          protocol: TCP
        - name: syslog-udp
          containerPort: 1514
          protocol: UDP
        - name: gelf-tcp
          containerPort: 12201
          protocol: TCP
        - name: gelf-udp
          containerPort: 12201
          protocol: UDP
        - name: forwarder-data
          containerPort: 13301
          protocol: TCP
        - name: forwarder-config
          containerPort: 13302
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/system/lbstatus
            port: http-port
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/system/lbstatus
            port: http-port
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - name: graylog
          mountPath: /usr/share/graylog/data
  volumeClaimTemplates:
  - metadata:
      name: graylog
    spec:
      storageClassName: nfs-client
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi