apiVersion: v1
kind: Service
metadata:
  name: redis-store
  namespace: redis
  labels:
    app: redis-store
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: redis-store