apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-security-config
  namespace: opensearch
  labels:
    component: opensearch
data:
  opensearch.yml: |
    plugins.security.ssl.transport.pemcert_filepath: willbridcom.pem
    plugins.security.ssl.transport.pemkey_filepath: willbridcom-key.pem
    plugins.security.ssl.transport.pemtrustedcas_filepath: willbridcom-ca.pem
    plugins.security.ssl.transport.enforce_hostname_verification: false
    plugins.security.ssl.http.enabled: true
    plugins.security.ssl.http.pemcert_filepath: willbridcom.pem
    plugins.security.ssl.http.pemkey_filepath: willbridcom-key.pem
    plugins.security.ssl.http.pemtrustedcas_filepath: willbridcom-ca.pem
    plugins.security.allow_default_init_securityindex: true
    plugins.security.authcz.admin_dn:
      - CN=*.willbrid.com,OU=willbrid,O=willbrid,L=DLA,ST=LT,C=CM
    plugins.security.nodes_dn:
      - 'CN=*.willbrid.com,OU=willbrid,O=willbrid,L=DLA,ST=LT,C=CM'
    plugins.security.audit.type: internal_opensearch
    plugins.security.enable_snapshot_restore_privilege: true
    plugins.security.check_snapshot_restore_write_privileges: true
    plugins.security.restapi.roles_enabled: ["all_access", "security_rest_api_access"]
    cluster.routing.allocation.disk.threshold_enabled: false
    opendistro_security.audit.config.disabled_rest_categories: NONE
    opendistro_security.audit.config.disabled_transport_categories: NONE