kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minio-storage
  labels:
    app: minio-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: custom-storage-class
  volumeMode: Filesystem