apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - name: tcp-port
    port: 27017
    targetPort: tcp-port
    protocol: TCP
  clusterIP: None
  selector:
    app: mongodb